# Generated by Django 5.2.4 on 2025-08-04 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("nickname", models.CharField(blank=True, max_length=50)),
                ("birth_date", models.DateField()),
                ("contact", models.CharField(max_length=13)),
                ("alternate_contact", models.CharField(blank=True, max_length=13)),
                ("email", models.EmailField(max_length=254)),
                ("alternate_email", models.EmailField(blank=True, max_length=254)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=60)),
                ("state", models.CharField(blank=True, max_length=60)),
                ("country", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
