# Generated by Django 5.2.4 on 2025-08-04 11:37

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=contacts.models.rename_contact_image
            ),
        ),
    ]
