# Generated by Django 5.2.4 on 2025-08-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Todo",
                "verbose_name_plural": "Todos",
            },
        ),
    ]
