# Generated by Django 5.2.4 on 2025-08-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_alter_todo_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
